services:

   apps:
     build: .
     command: 'python manage.py runserver 0.0.0.0:8000'
     container_name: DjangoBlog

     ports:
        - "8000:8000"
     env_file:
       - .env
     restart: always



#------------ if you use postgres db ---------
#   postgres:
#      image: postgres:latest
#      container_name: postgres
#      environment:
#         - POSTGRES_DB=BlogDb
#         - POSTGRES_USER=postgres
#         - POSTGRES_PASSWORD=root
#      ports:
#        - '5433:5432'
#      restart: always
#      volumes:
#         - postgres_data:/var/lib/docker/volumes/postgres_data/_data

#volumes:
#  postgres_data:



