services:
   postgres:
      image: postgres:latest
      container_name: postgres
      environment:
         - POSTGRES_DB=BlogDb
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=root
      ports:
        - '5433:5432'
      restart: always
      volumes:
         - postgres_data:/var/lib/docker/volumes/postgres_data/_data

   pgadmin:
     container_name: pgadmin4
     image: dpage/pgadmin4:latest
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@admin.com
       PGADMIN_DEFAULT_PASSWORD: secret
     ports:
       - "5050:80"

   apps:
     build: .
     command: 'python manage.py runserver 0.0.0.0:8000'
     container_name: DjangoBlog
     depends_on:
        - postgres
     ports:
        - "8000:8000"
     env_file:
       - .env
     restart: always



volumes:
  postgres_data:



