# Generated by Django 4.1.3 on 2022-11-10 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_unlikepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
