# Generated by Django 4.1.3 on 2022-11-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rate',
        ),
    ]
