# Generated by Django 4.1.3 on 2022-11-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blog_rate_ratepostform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratepostform',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratepost', to='blog.blog'),
        ),
    ]
