# Generated by Django 4.1.3 on 2022-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_ratepostform_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatePostForm',
            new_name='RatePost',
        ),
    ]
