# Generated by Django 4.1.3 on 2022-11-12 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_ratepost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlikepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='unlikepost',
            name='user',
        ),
        migrations.AlterField(
            model_name='ratepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postrate', to='blog.blog'),
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.DeleteModel(
            name='UnlikePost',
        ),
    ]
