# Generated by Django 4.1.3 on 2022-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='like',
            new_name='likes',
        ),
    ]
